services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=budgetbuddy
      - POSTGRES_USER=budgetbuddy
      - POSTGRES_PASSWORD=budgetbuddy
    ports:
      - "5432:5432"
