spring:
  application:
    name: budget-buddy-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  devtools:
    add-properties: false

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    secret: ${BUDGET_BUDDY_API_JWT_SECRET}
    access-token-validity-seconds: 900 # 15 minutes
    refresh-token-validity-seconds: 1209600 # 14 days

logging:
  level:
    root: INFO
