spring:
  docker:
    compose:
      enabled: false
  liquibase:
    contexts: prod
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false

security:
  cors:
    allowed-origin-patterns: ${BUDGET_BUDDY_API_CORS_ALLOWED_ORIGIN_PATTERNS}
  access-token:
    secret: ${BUDGET_BUDDY_API_ACCESS_TOKEN_SECRET}
    validity-seconds: ${BUDGET_BUDDY_API_ACCESS_TOKEN_VALIDITY_SECONDS}
  refresh-token:
    validity-seconds: ${BUDGET_BUDDY_API_REFRESH_TOKEN_VALIDITY_SECONDS}
    cleanup:
      enabled: true
      cron: "0 0 3 * * *"

logging:
  level:
    root: INFO
