spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.local.yaml
  liquibase:
    contexts: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  cors:
    allowed-origin-patterns:
      - "http://localhost:[*]"
logging:
  level:
    root: INFO
    web: DEBUG
    com.budget.buddy.budget_buddy_api: TRACE
    org.springframework:
      jdbc: DEBUG
      security: DEBUG
    liquibase: DEBUG
