spring:
  application:
    name: budget-buddy-api
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
  cache:
    type: caffeine
    cache-names:
      - oidcUsers
    caffeine:
      spec: >
        initialCapacity=50,
        maximumSize=200,
        expireAfterWrite=24h

server:
  port: ${SERVER_PORT:8080}

security:
  cors:
    allowed-origin-patterns: [ ]
    allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
    allowed-headers: [ "*" ]
    allow-credentials: true
    max-age: 3600
