spring:
  docker:
    compose:
      enabled: true
      profiles:
        active: "postgres"
      file: docker-compose.local.yaml

server:
  port: 8080

security:
  jwt:
    access-token-validity-seconds: 86400 # 1 day
    refresh-token-validity-seconds: 1209600 # 14 days

logging:
  level:
    web: DEBUG
    com.budget.buddy.budget_buddy_api: TRACE
    org.springframework:
      jdbc: DEBUG
      security: DEBUG
