spring:
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test-issuer.example.com
          audiences:
            - budget-buddy-api

security:
  cors:
    allowed-origin-patterns:
      - "http://localhost:[*]"
